name: Update README

on:
  workflow_call:

concurrency:
  group: update-readme-commit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: speckle-helm
      - name: Checkout this repository's gh-pages branch
        # This is the branch where the README.md will be updated
        uses: actions/checkout@v4
        with:
          path: speckle-helm-gh-pages
          ref: gh-pages
          sparse-checkout: README.md
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v4
        with:
          repository: bitnami-labs/readme-generator-for-helm
          ref: b578e769018136d02d12f01c99cf1334c897d24a # Use a specific commit to ensure consistency
          path: readme-generator-for-helm
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: readme-generator-for-helm/package-lock.json
      - name: Install Readme Generator
        run: |
          pushd ${{ github.workspace }}/readme-generator-for-helm
          npm install
          popd
      - name: Generate README
        run: |
          node "${{ github.workspace }}/readme-generator-for-helm/bin/index.js" \
            --config "${{ github.workspace }}/speckle-helm/.helm-readme-configuration.json" \
            --values "${{ github.workspace }}/speckle-helm/charts/speckle-server/values.yaml" \
            --readme "${{ github.workspace }}/speckle-helm-gh-pages/README.md"
      - name: Commit and push changes to main branch
        run: |
          pushd ${{ github.workspace }}/speckle-helm-gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          if [[ $(git status --porcelain) ]]; then
            git add README.md
            git commit -am "Updating README with revised parameters from values.yaml of Helm Chart."
            git push --set-upstream origin gh-pages
          fi
          popd
